//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace OasysUnits.Units
{
    // Disable missing XML comment warnings for the generated unit enums.
    #pragma warning disable 1591

    public enum MomentPerLengthUnit
    {
        KilogramForceCentimeterPerCentimeter = 4,
        KilogramForceMeterPerCentimeter = 3,
        KilogramForceMeterPerMeter = 8,
        KilogramForceMeterPerMillimeter = 6,
        KilogramForceMillimeterPerMillimeter = 10,
        KilonewtonCentimeterPerCentimeter = 7,
        KilonewtonMeterPerCentimeter = 5,
        KilonewtonMeterPerMeter = 9,
        KilonewtonMeterPerMillimeter = 2,
        KilonewtonMillimeterPerMillimeter = 1,
        KilopoundForceFootPerFoot = 14,
        KilopoundForceFootPerInch = 13,
        KilopoundForceInchPerInch = 17,
        MeganewtonCentimeterPerCentimeter = 18,
        MeganewtonMeterPerCentimeter = 19,
        MeganewtonMeterPerMeter = 11,
        MeganewtonMeterPerMillimeter = 20,
        MeganewtonMillimeterPerMillimeter = 12,
        NewtonCentimeterPerCentimeter = 16,
        NewtonMeterPerCentimeter = 15,
        NewtonMeterPerMeter = 30,
        NewtonMeterPerMillimeter = 21,
        NewtonMillimeterPerMillimeter = 28,
        PoundForceFootPerFoot = 22,
        PoundForceFootPerInch = 27,
        PoundForceFootPerYard = 23,
        PoundForceInchPerInch = 25,
        TonneForceCentimeterPerCentimeter = 24,
        TonneForceMeterPerCentimeter = 29,
        TonneForceMeterPerMeter = 26,
        TonneForceMeterPerMillimeter = 33,
        TonneForceMillimeterPerMillimeter = 35,
    }

    #pragma warning restore 1591
}
