//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace OasysUnits.Units
{
    // Disable missing XML comment warnings for the generated unit enums.
    #pragma warning disable 1591

    public enum MomentUnit
    {
        KilogramForceCentimeter = 5,
        KilogramForceMeter = 3,
        KilogramForceMillimeter = 1,
        KilonewtonCentimeter = 6,
        KilonewtonMeter = 10,
        KilonewtonMillimeter = 4,
        KilopoundForceFoot = 2,
        KilopoundForceInch = 7,
        MeganewtonCentimeter = 9,
        MeganewtonMeter = 8,
        MeganewtonMillimeter = 18,
        MegapoundForceFoot = 20,
        MegapoundForceInch = 14,
        NewtonCentimeter = 16,
        NewtonMeter = 17,
        NewtonMillimeter = 19,
        PoundalFoot = 11,
        PoundForceFoot = 13,
        PoundForceInch = 15,
        TonneForceCentimeter = 12,
        TonneForceMeter = 30,
        TonneForceMillimeter = 22,
    }

    #pragma warning restore 1591
}
