//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace OasysUnits.Units
{
    // Disable missing XML comment warnings for the generated unit enums.
    #pragma warning disable 1591

    public enum MomentUnit
    {
        KilogramForceCentimeter = 9,
        KilogramForceMeter = 6,
        KilogramForceMillimeter = 5,
        KilonewtonCentimeter = 8,
        KilonewtonMeter = 3,
        KilonewtonMillimeter = 2,
        KilopoundForceFoot = 1,
        KilopoundForceInch = 4,
        MeganewtonCentimeter = 10,
        MeganewtonMeter = 7,
        MeganewtonMillimeter = 15,
        MegapoundForceFoot = 13,
        MegapoundForceInch = 16,
        NewtonCentimeter = 19,
        NewtonMeter = 11,
        NewtonMillimeter = 14,
        PoundalFoot = 20,
        PoundForceFoot = 17,
        PoundForceInch = 12,
        TonneForceCentimeter = 18,
        TonneForceMeter = 21,
        TonneForceMillimeter = 28,
    }

    #pragma warning restore 1591
}
