//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace OasysUnits.Units
{
    // Disable missing XML comment warnings for the generated unit enums.
    #pragma warning disable 1591

    public enum MomentPerLengthUnit
    {
        KilogramForceCentimeterPerCentimeter = 8,
        KilogramForceMeterPerCentimeter = 2,
        KilogramForceMeterPerMeter = 1,
        KilogramForceMeterPerMillimeter = 9,
        KilogramForceMillimeterPerMillimeter = 10,
        KilonewtonCentimeterPerCentimeter = 4,
        KilonewtonMeterPerCentimeter = 7,
        KilonewtonMeterPerMeter = 6,
        KilonewtonMeterPerMillimeter = 5,
        KilonewtonMillimeterPerMillimeter = 3,
        KilopoundForceFootPerFoot = 20,
        KilopoundForceFootPerInch = 13,
        KilopoundForceInchPerFoot = 11,
        KilopoundForceInchPerInch = 12,
        MeganewtonCentimeterPerCentimeter = 19,
        MeganewtonMeterPerCentimeter = 17,
        MeganewtonMeterPerMeter = 15,
        MeganewtonMeterPerMillimeter = 18,
        MeganewtonMillimeterPerMillimeter = 14,
        NewtonCentimeterPerCentimeter = 16,
        NewtonMeterPerCentimeter = 30,
        NewtonMeterPerMeter = 21,
        NewtonMeterPerMillimeter = 26,
        NewtonMillimeterPerMillimeter = 24,
        PoundForceFootPerFoot = 28,
        PoundForceFootPerInch = 25,
        PoundForceFootPerYard = 27,
        PoundForceInchPerFoot = 29,
        PoundForceInchPerInch = 23,
        TonneForceCentimeterPerCentimeter = 22,
        TonneForceMeterPerCentimeter = 36,
        TonneForceMeterPerMeter = 33,
        TonneForceMeterPerMillimeter = 40,
        TonneForceMillimeterPerMillimeter = 34,
    }

    #pragma warning restore 1591
}
