//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace OasysUnits.Units
{
    // Disable missing XML comment warnings for the generated unit enums.
    #pragma warning disable 1591

    public enum MomentPerLengthUnit
    {
        KilogramForceCentimeterPerCentimeter = 16,
        KilogramForceMeterPerCentimeter = 11,
        KilogramForceMeterPerMeter = 17,
        KilogramForceMeterPerMillimeter = 15,
        KilogramForceMillimeterPerMillimeter = 14,
        KilonewtonCentimeterPerCentimeter = 26,
        KilonewtonMeterPerCentimeter = 27,
        KilonewtonMeterPerMeter = 28,
        KilonewtonMeterPerMillimeter = 25,
        KilonewtonMillimeterPerMillimeter = 24,
        KilopoundForceFootPerFoot = 21,
        KilopoundForceFootPerInch = 22,
        KilopoundForceInchPerFoot = 65,
        KilopoundForceInchPerInch = 30,
        MeganewtonCentimeterPerCentimeter = 23,
        MeganewtonMeterPerCentimeter = 29,
        MeganewtonMeterPerMeter = 39,
        MeganewtonMeterPerMillimeter = 40,
        MeganewtonMillimeterPerMillimeter = 34,
        NewtonCentimeterPerCentimeter = 45,
        NewtonMeterPerCentimeter = 41,
        NewtonMeterPerMeter = 59,
        NewtonMeterPerMillimeter = 54,
        NewtonMillimeterPerMillimeter = 57,
        PoundForceFootPerFoot = 52,
        PoundForceFootPerInch = 55,
        PoundForceFootPerYard = 58,
        PoundForceInchPerFoot = 61,
        PoundForceInchPerInch = 56,
        TonneForceCentimeterPerCentimeter = 51,
        TonneForceMeterPerCentimeter = 60,
        TonneForceMeterPerMeter = 62,
        TonneForceMeterPerMillimeter = 63,
        TonneForceMillimeterPerMillimeter = 70,
    }

    #pragma warning restore 1591
}
