//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;

namespace OasysUnits.Tests.CustomCode
{
    public class MomentPerLengthTests : MomentPerLengthTestsBase
    {
        protected override bool SupportsSIUnitSystem => false;
        protected override double KilogramForceCentimetersPerCentimeterInOneNewtonMeterPerMeter => 0.101971621;
        protected override double KilogramForceMetersPerCentimeterInOneNewtonMeterPerMeter => 0.00101971621;
        protected override double KilogramForceMetersPerMeterInOneNewtonMeterPerMeter => 0.101971621;
        protected override double KilogramForceMetersPerMillimeterInOneNewtonMeterPerMeter => 0.000101971621;
        protected override double KilogramForceMillimetersPerMillimeterInOneNewtonMeterPerMeter => 0.101971621;
        protected override double KilonewtonCentimetersPerCentimeterInOneNewtonMeterPerMeter => 0.001;
        protected override double KilonewtonMetersPerCentimeterInOneNewtonMeterPerMeter => 0.00001;
        protected override double KilonewtonMetersPerMeterInOneNewtonMeterPerMeter => 0.001;
        protected override double KilonewtonMetersPerMillimeterInOneNewtonMeterPerMeter => 0.000001;
        protected override double KilonewtonMillimetersPerMillimeterInOneNewtonMeterPerMeter => 0.001;
        protected override double KilopoundForceFeetPerFootInOneNewtonMeterPerMeter => 0.00022481;
        protected override double KilopoundForceFeetPerInchInOneNewtonMeterPerMeter => 0.000018734167;
        protected override double KilopoundForceInchesPerInchInOneNewtonMeterPerMeter => 0.00022481;
        protected override double MeganewtonCentimetersPerCentimeterInOneNewtonMeterPerMeter => 1E-6;
        protected override double MeganewtonMetersPerCentimeterInOneNewtonMeterPerMeter => 1E-8;
        protected override double MeganewtonMetersPerMeterInOneNewtonMeterPerMeter => 1E-6;
        protected override double MeganewtonMetersPerMillimeterInOneNewtonMeterPerMeter => 1E-9;
        protected override double MeganewtonMillimetersPerMillimeterInOneNewtonMeterPerMeter => 1E-6;
        protected override double NewtonCentimetersPerCentimeterInOneNewtonMeterPerMeter => 1;
        protected override double NewtonMetersPerCentimeterInOneNewtonMeterPerMeter => 0.01;
        protected override double NewtonMetersPerMeterInOneNewtonMeterPerMeter => 1;
        protected override double NewtonMetersPerMillimeterInOneNewtonMeterPerMeter => 0.001;
        protected override double NewtonMillimetersPerMillimeterInOneNewtonMeterPerMeter => 1;
        protected override double PoundForceFeetPerFootInOneNewtonMeterPerMeter => 0.22481;
        protected override double PoundForceFeetPerInchInOneNewtonMeterPerMeter => 0.018734167;
        protected override double PoundForceFeetPerYardInOneNewtonMeterPerMeter => 0.67443;
        protected override double PoundForceInchesPerInchInOneNewtonMeterPerMeter => 0.22481;
        protected override double TonneForceCentimetersPerCentimeterInOneNewtonMeterPerMeter => 1.01972e-4;
        protected override double TonneForceMetersPerCentimeterInOneNewtonMeterPerMeter => 1.01972e-6;
        protected override double TonneForceMetersPerMeterInOneNewtonMeterPerMeter => 1.01972e-4;
        protected override double TonneForceMetersPerMillimeterInOneNewtonMeterPerMeter => 1.01972e-7;
        protected override double TonneForceMillimetersPerMillimeterInOneNewtonMeterPerMeter => 1.01972e-4;
    }
}
