//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/OasysUnits/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/OasysUnits.

using System;

#if NET7_0_OR_GREATER
using System.Numerics;
#endif

#nullable enable

namespace OasysUnits.NumberExtensions.NumberToMoment
{
    /// <summary>
    /// A number to Moment Extensions
    /// </summary>
    public static class NumberToMomentExtensions
    {
        /// <inheritdoc cref="Moment.FromKilogramForceCentimeters(double)" />
        public static Moment KilogramForceCentimeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromKilogramForceCentimeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromKilogramForceMeters(double)" />
        public static Moment KilogramForceMeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromKilogramForceMeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromKilogramForceMillimeters(double)" />
        public static Moment KilogramForceMillimeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromKilogramForceMillimeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromKilonewtonCentimeters(double)" />
        public static Moment KilonewtonCentimeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromKilonewtonCentimeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromKilonewtonMeters(double)" />
        public static Moment KilonewtonMeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromKilonewtonMeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromKilonewtonMillimeters(double)" />
        public static Moment KilonewtonMillimeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromKilonewtonMillimeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromKilopoundForceFeet(double)" />
        public static Moment KilopoundForceFeet<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromKilopoundForceFeet(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromKilopoundForceInches(double)" />
        public static Moment KilopoundForceInches<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromKilopoundForceInches(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromMeganewtonCentimeters(double)" />
        public static Moment MeganewtonCentimeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromMeganewtonCentimeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromMeganewtonMeters(double)" />
        public static Moment MeganewtonMeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromMeganewtonMeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromMeganewtonMillimeters(double)" />
        public static Moment MeganewtonMillimeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromMeganewtonMillimeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromMegapoundForceFeet(double)" />
        public static Moment MegapoundForceFeet<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromMegapoundForceFeet(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromMegapoundForceInches(double)" />
        public static Moment MegapoundForceInches<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromMegapoundForceInches(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromNewtonCentimeters(double)" />
        public static Moment NewtonCentimeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromNewtonCentimeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromNewtonMeters(double)" />
        public static Moment NewtonMeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromNewtonMeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromNewtonMillimeters(double)" />
        public static Moment NewtonMillimeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromNewtonMillimeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromPoundalFeet(double)" />
        public static Moment PoundalFeet<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromPoundalFeet(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromPoundForceFeet(double)" />
        public static Moment PoundForceFeet<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromPoundForceFeet(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromPoundForceInches(double)" />
        public static Moment PoundForceInches<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromPoundForceInches(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromTonneForceCentimeters(double)" />
        public static Moment TonneForceCentimeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromTonneForceCentimeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromTonneForceMeters(double)" />
        public static Moment TonneForceMeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromTonneForceMeters(Convert.ToDouble(value));

        /// <inheritdoc cref="Moment.FromTonneForceMillimeters(double)" />
        public static Moment TonneForceMillimeters<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Moment.FromTonneForceMillimeters(Convert.ToDouble(value));

    }
}
