//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;

#if NET7_0_OR_GREATER
using System.Numerics;
#endif

#nullable enable

namespace OasysUnits.NumberExtensions.NumberToJerk
{
    /// <summary>
    /// A number to Jerk Extensions
    /// </summary>
    public static class NumberToJerkExtensions
    {
        /// <inheritdoc cref="Jerk.FromCentimetersPerSecondCubed(OasysUnits.QuantityValue)" />
        public static Jerk CentimetersPerSecondCubed<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Jerk.FromCentimetersPerSecondCubed(Convert.ToDouble(value));

        /// <inheritdoc cref="Jerk.FromDecimetersPerSecondCubed(OasysUnits.QuantityValue)" />
        public static Jerk DecimetersPerSecondCubed<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Jerk.FromDecimetersPerSecondCubed(Convert.ToDouble(value));

        /// <inheritdoc cref="Jerk.FromFeetPerSecondCubed(OasysUnits.QuantityValue)" />
        public static Jerk FeetPerSecondCubed<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Jerk.FromFeetPerSecondCubed(Convert.ToDouble(value));

        /// <inheritdoc cref="Jerk.FromInchesPerSecondCubed(OasysUnits.QuantityValue)" />
        public static Jerk InchesPerSecondCubed<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Jerk.FromInchesPerSecondCubed(Convert.ToDouble(value));

        /// <inheritdoc cref="Jerk.FromKilometersPerSecondCubed(OasysUnits.QuantityValue)" />
        public static Jerk KilometersPerSecondCubed<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Jerk.FromKilometersPerSecondCubed(Convert.ToDouble(value));

        /// <inheritdoc cref="Jerk.FromMetersPerSecondCubed(OasysUnits.QuantityValue)" />
        public static Jerk MetersPerSecondCubed<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Jerk.FromMetersPerSecondCubed(Convert.ToDouble(value));

        /// <inheritdoc cref="Jerk.FromMicrometersPerSecondCubed(OasysUnits.QuantityValue)" />
        public static Jerk MicrometersPerSecondCubed<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Jerk.FromMicrometersPerSecondCubed(Convert.ToDouble(value));

        /// <inheritdoc cref="Jerk.FromMillimetersPerSecondCubed(OasysUnits.QuantityValue)" />
        public static Jerk MillimetersPerSecondCubed<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Jerk.FromMillimetersPerSecondCubed(Convert.ToDouble(value));

        /// <inheritdoc cref="Jerk.FromMillistandardGravitiesPerSecond(OasysUnits.QuantityValue)" />
        public static Jerk MillistandardGravitiesPerSecond<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Jerk.FromMillistandardGravitiesPerSecond(Convert.ToDouble(value));

        /// <inheritdoc cref="Jerk.FromNanometersPerSecondCubed(OasysUnits.QuantityValue)" />
        public static Jerk NanometersPerSecondCubed<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Jerk.FromNanometersPerSecondCubed(Convert.ToDouble(value));

        /// <inheritdoc cref="Jerk.FromStandardGravitiesPerSecond(OasysUnits.QuantityValue)" />
        public static Jerk StandardGravitiesPerSecond<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => Jerk.FromStandardGravitiesPerSecond(Convert.ToDouble(value));

    }
}
