//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;

#if NET7_0_OR_GREATER
using System.Numerics;
#endif

#nullable enable

namespace OasysUnits.NumberExtensions.NumberToPowerDensity
{
    /// <summary>
    /// A number to PowerDensity Extensions
    /// </summary>
    public static class NumberToPowerDensityExtensions
    {
        /// <inheritdoc cref="PowerDensity.FromDecawattsPerCubicFoot(OasysUnits.QuantityValue)" />
        public static PowerDensity DecawattsPerCubicFoot<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromDecawattsPerCubicFoot(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromDecawattsPerCubicInch(OasysUnits.QuantityValue)" />
        public static PowerDensity DecawattsPerCubicInch<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromDecawattsPerCubicInch(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromDecawattsPerCubicMeter(OasysUnits.QuantityValue)" />
        public static PowerDensity DecawattsPerCubicMeter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromDecawattsPerCubicMeter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromDecawattsPerLiter(OasysUnits.QuantityValue)" />
        public static PowerDensity DecawattsPerLiter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromDecawattsPerLiter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromDeciwattsPerCubicFoot(OasysUnits.QuantityValue)" />
        public static PowerDensity DeciwattsPerCubicFoot<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromDeciwattsPerCubicFoot(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromDeciwattsPerCubicInch(OasysUnits.QuantityValue)" />
        public static PowerDensity DeciwattsPerCubicInch<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromDeciwattsPerCubicInch(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromDeciwattsPerCubicMeter(OasysUnits.QuantityValue)" />
        public static PowerDensity DeciwattsPerCubicMeter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromDeciwattsPerCubicMeter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromDeciwattsPerLiter(OasysUnits.QuantityValue)" />
        public static PowerDensity DeciwattsPerLiter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromDeciwattsPerLiter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromGigawattsPerCubicFoot(OasysUnits.QuantityValue)" />
        public static PowerDensity GigawattsPerCubicFoot<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromGigawattsPerCubicFoot(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromGigawattsPerCubicInch(OasysUnits.QuantityValue)" />
        public static PowerDensity GigawattsPerCubicInch<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromGigawattsPerCubicInch(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromGigawattsPerCubicMeter(OasysUnits.QuantityValue)" />
        public static PowerDensity GigawattsPerCubicMeter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromGigawattsPerCubicMeter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromGigawattsPerLiter(OasysUnits.QuantityValue)" />
        public static PowerDensity GigawattsPerLiter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromGigawattsPerLiter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromKilowattsPerCubicFoot(OasysUnits.QuantityValue)" />
        public static PowerDensity KilowattsPerCubicFoot<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromKilowattsPerCubicFoot(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromKilowattsPerCubicInch(OasysUnits.QuantityValue)" />
        public static PowerDensity KilowattsPerCubicInch<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromKilowattsPerCubicInch(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromKilowattsPerCubicMeter(OasysUnits.QuantityValue)" />
        public static PowerDensity KilowattsPerCubicMeter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromKilowattsPerCubicMeter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromKilowattsPerLiter(OasysUnits.QuantityValue)" />
        public static PowerDensity KilowattsPerLiter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromKilowattsPerLiter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromMegawattsPerCubicFoot(OasysUnits.QuantityValue)" />
        public static PowerDensity MegawattsPerCubicFoot<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromMegawattsPerCubicFoot(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromMegawattsPerCubicInch(OasysUnits.QuantityValue)" />
        public static PowerDensity MegawattsPerCubicInch<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromMegawattsPerCubicInch(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromMegawattsPerCubicMeter(OasysUnits.QuantityValue)" />
        public static PowerDensity MegawattsPerCubicMeter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromMegawattsPerCubicMeter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromMegawattsPerLiter(OasysUnits.QuantityValue)" />
        public static PowerDensity MegawattsPerLiter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromMegawattsPerLiter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromMicrowattsPerCubicFoot(OasysUnits.QuantityValue)" />
        public static PowerDensity MicrowattsPerCubicFoot<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromMicrowattsPerCubicFoot(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromMicrowattsPerCubicInch(OasysUnits.QuantityValue)" />
        public static PowerDensity MicrowattsPerCubicInch<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromMicrowattsPerCubicInch(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromMicrowattsPerCubicMeter(OasysUnits.QuantityValue)" />
        public static PowerDensity MicrowattsPerCubicMeter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromMicrowattsPerCubicMeter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromMicrowattsPerLiter(OasysUnits.QuantityValue)" />
        public static PowerDensity MicrowattsPerLiter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromMicrowattsPerLiter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromMilliwattsPerCubicFoot(OasysUnits.QuantityValue)" />
        public static PowerDensity MilliwattsPerCubicFoot<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromMilliwattsPerCubicFoot(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromMilliwattsPerCubicInch(OasysUnits.QuantityValue)" />
        public static PowerDensity MilliwattsPerCubicInch<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromMilliwattsPerCubicInch(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromMilliwattsPerCubicMeter(OasysUnits.QuantityValue)" />
        public static PowerDensity MilliwattsPerCubicMeter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromMilliwattsPerCubicMeter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromMilliwattsPerLiter(OasysUnits.QuantityValue)" />
        public static PowerDensity MilliwattsPerLiter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromMilliwattsPerLiter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromNanowattsPerCubicFoot(OasysUnits.QuantityValue)" />
        public static PowerDensity NanowattsPerCubicFoot<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromNanowattsPerCubicFoot(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromNanowattsPerCubicInch(OasysUnits.QuantityValue)" />
        public static PowerDensity NanowattsPerCubicInch<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromNanowattsPerCubicInch(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromNanowattsPerCubicMeter(OasysUnits.QuantityValue)" />
        public static PowerDensity NanowattsPerCubicMeter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromNanowattsPerCubicMeter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromNanowattsPerLiter(OasysUnits.QuantityValue)" />
        public static PowerDensity NanowattsPerLiter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromNanowattsPerLiter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromPicowattsPerCubicFoot(OasysUnits.QuantityValue)" />
        public static PowerDensity PicowattsPerCubicFoot<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromPicowattsPerCubicFoot(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromPicowattsPerCubicInch(OasysUnits.QuantityValue)" />
        public static PowerDensity PicowattsPerCubicInch<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromPicowattsPerCubicInch(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromPicowattsPerCubicMeter(OasysUnits.QuantityValue)" />
        public static PowerDensity PicowattsPerCubicMeter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromPicowattsPerCubicMeter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromPicowattsPerLiter(OasysUnits.QuantityValue)" />
        public static PowerDensity PicowattsPerLiter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromPicowattsPerLiter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromTerawattsPerCubicFoot(OasysUnits.QuantityValue)" />
        public static PowerDensity TerawattsPerCubicFoot<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromTerawattsPerCubicFoot(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromTerawattsPerCubicInch(OasysUnits.QuantityValue)" />
        public static PowerDensity TerawattsPerCubicInch<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromTerawattsPerCubicInch(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromTerawattsPerCubicMeter(OasysUnits.QuantityValue)" />
        public static PowerDensity TerawattsPerCubicMeter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromTerawattsPerCubicMeter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromTerawattsPerLiter(OasysUnits.QuantityValue)" />
        public static PowerDensity TerawattsPerLiter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromTerawattsPerLiter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromWattsPerCubicFoot(OasysUnits.QuantityValue)" />
        public static PowerDensity WattsPerCubicFoot<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromWattsPerCubicFoot(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromWattsPerCubicInch(OasysUnits.QuantityValue)" />
        public static PowerDensity WattsPerCubicInch<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromWattsPerCubicInch(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromWattsPerCubicMeter(OasysUnits.QuantityValue)" />
        public static PowerDensity WattsPerCubicMeter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromWattsPerCubicMeter(Convert.ToDouble(value));

        /// <inheritdoc cref="PowerDensity.FromWattsPerLiter(OasysUnits.QuantityValue)" />
        public static PowerDensity WattsPerLiter<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
#endif
            => PowerDensity.FromWattsPerLiter(Convert.ToDouble(value));

    }
}
